### ISSUE TITLE
Backend code - Use USDA API, call the API with parameters, extract all the required nutrition information and save it in user database. Please check the userdata.js file in static/JS folder to understand what all nutrition parameters are required.

### ISSUE THREAD

**Issue by PGGokhale** [Rebel-Scum-Analytical/TeamProject2#16]

**Comment by look4parul** [comment]
Created USDA database with tables and data

**Comment by look4parul** [comment]
Migrate the tables from usda data base (MS Accord)  to mysql and export the required columns with entire data to file1.csv under db folder.
Created the nutrition table with entire data and nutrition information and this table is used to display stats on dashboard page and visualizations.
